### ISSUE TITLE
LMS Client v8+

### ISSUE THREAD

**Issue by edisontoo** [bklaas/fontreplacer#3]
As LMS has progressed to v8.1.1, there are also community client firmware that are version 8 and above. But Font Replacer is not available on these client as the maxTarget Version in the repo.xml is set at 7.*.

Please update Font Replacer so that it is available on higher version clients. Thanks.

**Comment by bklaas** [comment]
Updated maxTarget to 8.*

**Comment by edisontoo** [comment]
Thanks for the quick response, however testing shows that Font Replacer is still not showing up on v8+ clients. I notice that the Applet version in repo.xml is listed as "1.1", however I have been using "Font Replacer 1.3" for some time already. Could it be that the current repository is pointing to a different Font Replacer (v1.3) somewhere else?

Thanks for looking into this. Best regards.

**Comment by bklaas** [comment]
I've bumped the repo .xml to list this as 1.4, but looking back over my email, it looks like the zip file is now hosted by Michael Herger, who is still keeping squeezenetwork afloat from the Swiss Alps. I am going to contact him about getting that side of things updated, as it won't work until that happens.

**Comment by bklaas** [comment]
@edisontoo I spoke with Michael and I think we've got it worked out. I have a repo.xml file that I host that points to a URL that Michael hosts. I updated my repo.xml file to point to the updated URL http://downloads.nixda.ch/FontReplacer-1.4.zip. Michael just needs to get that file in place and it should work against LMS 8.*

**Comment by bklaas** [comment]
File has been made available on Michael's download server. Closing this, but let me know how hit goes as I have no easy way to test!

**Comment by edisontoo** [comment]
Thanks again Ben, I've tested it, I can now see Font Replacer applet and install it. However, upon restart, there is no menu item that allows me to install the fonts. If I go into Applet menu, it just allows me to reinstall Font Replacer, which does not solve the problem. Since Font Replacer has been working all along, I'll check with the Client Firmware author to see if there is anything in v8+ clients that may prevent Font Replacer from working. Thanks again, will update if there is any progress.

**Comment by edisontoo** [comment]
Hi, the Client Firmware author did some testing and found that the zip archive of v1.3 and v1.4 is different. There is an extra level of redundant directory in the archive causing the failure. It'll be easier if you just take a look at the ticket [https://sourceforge.net/p/lmsclients/tickets/5/](url). If you can update the v1.4 zip archive, things should be working again. Thanks!

**Comment by bklaas** [comment]
New zip file sent to Michael that removes directory structure and just contains the code. Should work after Michael drops the new file on his server. He's usually very quick to respond, so this should happen soon.

**Comment by bklaas** [comment]
File should be up to date now, let me know how it goes @edisontoo 

note: the url of the new zip is http://downloads.nixda.ch/FontReplacer-1.4a.zip, which is what my repo.xml points to now

**Comment by edisontoo** [comment]
Thanks Ben, but testing shows that its still not working though the 1.4a.zp you provided above looks correct. However, the url in repo.xml seems to be pointing at github archive, is that correct?

**Comment by bklaas** [comment]
According to Michael the repo.xml file that's used by LMS and SqueezeNetwork is from my personal webserver at https://benklaas.com/fontreplacer.repo.xml
So, that's the file I've been updating. Here are its contents:

```
<?xml version="1.0"?>

<extensions>

  <details>
        <title lang="EN">Ben Klaas community plugins/applets</title>
  </details>

  <applets>

        <applet name="FontReplacer" version="1.4" minTarget="7.3" maxTarget="8.*">
          <title lang="EN">Font Replacer</title>
          <desc  lang="EN">Replaces the default FreeSans Font with a merged FreeSans + DroidSansFallback font to provide a fuller character set, including Chinese/Japanese/Korean characters</desc>
          <url>http://downloads.nixda.ch/FontReplacer-1.4a.zip</url>
          <email>mcstayinskool@yahoo.com</email>
          <sha>622cd1c113973ab5f1143ecc6343988baa0da3fb</sha>
        </applet>

  </applets>

</extensions>
```
I will go ahead and change the one on github to match this one, but I don't think it's in use.

**Comment by bklaas** [comment]
The github repo.xml file is now identical to the one on benklaas.com.
Ideally repo.xml on github would be the one LMS/SqueezeNetwork would use, but I think there's a technical reason why that won't work (?)
Regardless, they are the same now, so that elminates github.com version as being an issue. Both point to http://downloads.nixda.ch/FontReplacer-1.4a.zip for the zip file.

**Comment by bklaas** [comment]
Reopening this, but also not sure what else to try...

**Comment by edisontoo** [comment]
Thanks, I still have no luck getting it to work. Will see if the firmware author can find any clue. Regards.

**Comment by edisontoo** [comment]
Hi, Ralph found that the checksum for the zip file was not updated in the repo.xml, which resulted in the failed installation. Do check that up, thanks.

**Comment by bklaas** [comment]
sha sum updated in repo.xml, both on my webserver and in git repo. checksum reflects the sha for FontReplacer-1.4a.zip on the nixda.ch server.

**Comment by edisontoo** [comment]
Yes, it's working now! I have tested on Radio and Touch, for those who upgraded to v8+ client firmware, the Font Replacer 1.4 will show up and install as previously done. For those who have upgraded before this fix, reinstalling may not work, they may have to downgrade the firmware to v7.7+ and upgrade to v8+ firmware again for it to install properly.

Thanks for your help, Ben, regards.

**Comment by bklaas** [comment]
Excellent!
