### ISSUE TITLE
fontreplacer is not showing up in applet list

### ISSUE THREAD

**Issue by teoleonghwee** [bklaas/fontreplacer#5]
Hi bklass,

fontreplacer is not showing up in the applet list. Is there something you need to fix regarding the repository?

Thanks,
Leon

**Comment by bklaas** [comment]
There have been no changes on the fontreplacer side and I confirmed that the URL for the download still works.

Is there any chance the major version of the software has gone past 8?
fontreplacer will show up in the list for versions >= 7.3 up to anything starting with 8
`<applet name="FontReplacer" version="1.4" minTarget="7.3" maxTarget="8.*">`
If the version has gone to 9 I can update this parameter, that might be the fix.

**Comment by michaelherger** [comment]
Hi @bklaas - good to see you still around 😀.

There seems to be a problem with your host not responding.

```
 % curl -I https://benklaas.com/fontreplacer/repo.xml
curl: (7) Failed to connect to benklaas.com port 443 after 6145 ms: Couldn't connect to server
```

See also https://github.com/LMS-Community/lms-plugin-repository/actions/runs/5393345243/jobs/9792950802#step:4:8

**Comment by bklaas** [comment]
Guten Tag @michaelherger!
Well that makes sense, the UPS that powers benklaas.com died last night.
However...repo.xml points to the Swiss URL you setup for this years ago. Is there somewhere else the updated URL needs to go?
`<url>http://downloads.nixda.ch/FontReplacer-1.4a.zip</url>` <-- from repo.xml

**Comment by michaelherger** [comment]
Hmm... where's that URL coming from? I might have created this at some point, but the current repository is pointing at the above URL I posted.

**Comment by bklaas** [comment]
it's from repo.xml in this repository
https://github.com/bklaas/fontreplacer/blob/master/repo.xml

**Comment by michaelherger** [comment]
Oh, I should use that URL then. Might be slightly more reliable than your UPS 😁.

**Comment by bklaas** [comment]
we covered this ground a few years ago. 
https://github.com/bklaas/fontreplacer/issues/2
surprised it reverted to going back to benklaas.com, which I wouldn't have thought would work because I redirect all http to https and from the issue discussion that wouldn't work?

**Comment by bklaas** [comment]
I'll have a new UPS soon though :)

**Comment by michaelherger** [comment]
I'm not sure when that got lost. Maybe when I moved the repo handling to its own Github repository. So thanks for the reminder! 

The main repo file should be good again: https://github.com/LMS-Community/lms-plugin-repository/commit/9c65a8dcea9536f9853d25c835b5b415cf1f2fe8. @teoleonghwee - please give it a try later today or tomorrow. It might take a moment for caches to be expired etc.

**Comment by teoleonghwee** [comment]
Thanks to both of you! fontreplacer appeared and successfully installed. Really appreciate you taking time to address this!
